Python 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
= RESTART: D:/project/Python/School/P_turtle.py
>>> t1=turtle.Turtle()
>>> t1.color("red)
...          
SyntaxError: incomplete input
>>> t1.color("red")
...          
>>> t1.forward(200)
...          
>>> t2=turtle.Turtle()
...          
>>> t2.color("blue")
...          
>>> t2.left(90)
...          
>>> t2.forward(300)
...          
>>> t3=turtle.Turtle()
...          
>>> t3.right(180)
...          
>>> t3.forward(100)
...          
>>> t3.left(90)
...          
>>> t3.forward(30)
...          
